# Generated by Django 5.0.8 on 2024-08-15 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 10, 25, 39, 976573, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
